# A sample Makefile for building Google Test and using it in user
# tests.  Please tweak it to suit your environment and project.  You
# may want to move it to your project's root directory.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Please tweak the following variable definitions as needed by your
# project, except GTEST_HEADERS, which you can use in your own targets
# but shouldn't modify.

# Points to the root of Google Test, relative to where this file is.
# Remember to tweak this if you move this file.
GTEST_DIR = /home/leivaa/Escritorio/projectis/googletest/googletest

# Where to find user code.
# USER_DIR = ../samples

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -isystem $(GTEST_DIR)/include

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -pthread -std=gnu++11

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = ruta_unittest administrador_unittest sendero_unittest parque_unittest

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

# House-keeping build targets.
# make comienza con el primer target, el "default goal"
# que incluye $(TEST) y, por tanto, intentará constriur cada uno de esos ejecutables
all : $(TESTS)

clean :
	rm -f $(TESTS) gtest.a gtest_main.a *.o

# Builds gtest.a and gtest_main.a.

# Usually you shouldn't tweak such internal variables, indicated by a
# trailing _.
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

# For simplicity and to avoid depending on Google Test's
# implementation details, the dependencies specified below are
# conservative and not optimized.  This is fine as Google Test
# compiles fast and for ordinary users its source rarely changes.
gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $@ $^

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

# Builds a sample test.  A test should link with either gtest.a or
# gtest_main.a, depending on whether it defines its own main()
# function.

persona.o : persona.h persona.cc

visitante.o: visitante.h visitante.cc persona.h persona.cc

administrador.o: administrador.h administrador.cc persona.h persona.cc reserva.h reserva.cc visitante.h visitante.cc ruta.h ruta.cc sendero.h sendero.cc parque.h parque.cc monitor.h monitor.cc incidencia.h incidencia.cc

monitor.o: monitor.h monitor.cc persona.h persona.cc sendero.h sendero.cc incidencia.h incidencia.cc parque.h parque.cc ruta.h ruta.cc visitante.h visitante.cc

parque.o: parque.h parque.cc sendero.h sendero.cc incidencia.h incidencia.cc ruta.h ruta.cc visitante.h visitante.cc persona.h persona.cc

incidencia.o: incidencia.h incidencia.cc ruta.h ruta.cc visitante.h visitante.cc persona.h persona.cc sendero.h sendero.cc parque.h parque.cc

sendero.o: sendero.h sendero.cc incidencia.h incidencia.cc ruta.h ruta.cc visitante.h visitante.cc persona.h persona.cc parque.h parque.cc

ruta.o: ruta.h ruta.cc sendero.h sendero.cc visitante.h visitante.cc incidencia.h incidencia.cc persona.h persona.cc

reserva.o:  reserva.h reserva.cc ruta.h ruta.cc sendero.h sendero.cc incidencia.h incidencia.cc visitante.h visitante.cc persona.h persona.cc parque.h parque.cc

sendero_unittest.o: sendero_unittest.cc sendero.cc sendero.h

sendero_unittest: sendero_unittest.o sendero.o gtest_main.a

parque_unittest.o: parque_unittest.cc parque.cc parque.h 

parque_unittest: parque_unittest.o parque.o gtest_main.a

administrador_unittest.o: administrador_unittest.cc administrador.cc administrador.h

administrador_unittest: administrador_unittest.o administrador.o gtest_main.a

ruta_unittest.o : ruta_unittest.cc ruta.cc ruta.h 

ruta_unittest : ruta_unittest.o ruta.o sendero.o visitante.o incidencia.o persona.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@

